# -*- coding: utf-8 -*-
"""21107054(asg-4).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BmvLkz_PCB9gdXl3OBoAvmP5YMv8v4o3
"""

# Question 1

# User Input
marks = float(input('Enter your marks : '))

# Condition for grading

if marks<25:  
 print('Your grade is F')
elif 25<=marks<45:
 print('Your grade is E')
elif 45<=marks<50:
 print('Your grade is D')
elif 50<=marks<60:
 print('Your grade is C')
elif 60<=marks<=80:
 print('Your grade on B')
elif 80<marks<=100:
 print('Your grade is A ')
else: 
 print('Please enter correct number of marks ')

# Question 2 

# User input
year = int(input('Enter the year : '))

# Checking condition for leap year
if (year%4==0 and year%100!=0):
 print(year,'is a leap year')
elif (year%4==0 and year%100==0 and year%400==0):
 print(year,'is a leap year')
else:
  print(year,'is not a leap year')

# Question 3 

n = 10
while(n>0):
    n = n-1
    import random

    a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    num1 = random.choice(a)
    num2 = random.choice(a)
    print(num1, "x", num2)
    answer = int(input("Enter the correct answer:\n"))
    if answer == num1*num2:
        print("Correct")
    elif answer != num1*num2:
        print("Wrong!, the correct answer is ", num1*num2)
    print("Number of tries left:", n)

print("Thank you for playing the game.")

# Question 4

number=1
while number<200:
    if number%5 == 2 and number%6 == 3 and number%7 == 2:
        print("The number of candies is : " + str(number))
    number = number + 1